//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactFormular
    {
        public string Name { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email_Address { get; set; }
        public string Enquiry { get; set; }
    }
}
